### ISSUE TITLE
Issue with Preparing cmdstan_model

### ISSUE THREAD

**Issue by liujunjie19950913** [bernibra/nonlinear-stan#1]
Hello,

I've run into a problem while preparing the cmdstan_model as per the steps outlined in the README file, and I'm hoping to get some guidance on how to fix it. Here's what I've experienced:

1. I followed the installation instructions in the README carefully.
2. When I tried to execute the cmdstan_model preparation command, I encountered an error.
3. I've attached a screenshot of the error message below for your reference.
The operating system I'm working on is Windows x64 , and I'm using R4.0.4. All dependencies are current and have been verified. Could you please assist me in troubleshooting this error?

Thank you very much for your help.

![20240125225809](https://github.com/bernibra/nonlinear-stan/assets/130567533/fd8eb680-c4e1-4e0a-8002-2ec70cd22f2b)
Best regards,
Junjie Liu

**Comment by bernibra** [comment]
Hi Junjie Liu,

This looks like an issue with the installation of cmdstan in Windows. Have you tried going over the examples in the documentation page of cmdstan and cmdstanr? Does it compile for their examples? It's a little hard for me to know what the problem is just with the information that you provided, but I would suggest several things. First, if the same issues happen with the examples provided by cmdstanr, I would ask their developers for help in solving your installation issues. Second, if cmdstanr works for other examples but not the ones provided in my repo, I would make sure that all libraries match the version that I am using. Finally, if none of the above steps help, I would suggest running the code (with small L and N) in a virtual machine with `threads_per_chain = 1` and `parallel_chains = 1`.

All the best,
B
